-- Build a branded Keynote .key presentation from an outline JSON generated by markdown_to_outline.py
-- Usage on macOS with Keynote installed:
--   osascript build_keynote.applescript /absolute/path/outline.json /absolute/path/output.key
--
-- Branding rules:
-- - content slides: white background, black text, small logo watermark in top-right
-- - chapter slides: yellow (#ffed3a) background, black text, no watermark
-- - every slide receives presenter notes when Keynote exposes the presenter notes property
-- - logo is materialized from the skill asset, not from a temporary conversation attachment

on run argv
	if (count of argv) is not 2 then
		error "Usage: osascript build_keynote.applescript outline.json output.key"
	end if

	set outlinePath to item 1 of argv
	set outputPath to item 2 of argv
	set materializeCmd to "python3 /skills/keynote-generator/scripts/materialize_assets.py"
	do shell script materializeCmd

	set pythonCode to "import json,sys; d=json.load(open(sys.argv[1],encoding='utf-8')); logo=d.get('metadata',{}).get('logo_path','/workspace/work/keynote-generator-assets/aulab_logo_watermark_48.png')" & ¬
		"\nfor s in d.get('slides',[]):" & ¬
		"\n vals=[s.get('title','Untitled'), ' • '.join(s.get('bullets',[])), ' '.join(s.get('notes',[])), s.get('type','content'), str(bool(s.get('watermark', True))).lower(), s.get('background','#ffffff'), s.get('text_color','#000000'), logo]" & ¬
		"\n print('\\t'.join(v.replace('\\t',' ').replace('\\n',' ') for v in vals))"
	set cmd to "python3 -c " & quoted form of pythonCode & " " & quoted form of outlinePath
	set slideLines to paragraphs of (do shell script cmd)

	tell application "Keynote"
		activate
		set theDoc to make new document with properties {document theme:theme "White"}
		set slideWidth to slide width of theDoc
		set slideHeight to slide height of theDoc

		repeat with i from 1 to count of slideLines
			set slideLine to item i of slideLines
			set AppleScript's text item delimiters to tab
			set parts to text items of slideLine
			set AppleScript's text item delimiters to ""
			set slideTitle to item 1 of parts
			set slideBody to ""
			set slideNotes to ""
			set slideType to "content"
			set shouldWatermark to "true"
			set logoPath to "/workspace/work/keynote-generator-assets/aulab_logo_watermark_48.png"
			if (count of parts) >= 2 then set slideBody to item 2 of parts
			if (count of parts) >= 3 then set slideNotes to item 3 of parts
			if (count of parts) >= 4 then set slideType to item 4 of parts
			if (count of parts) >= 5 then set shouldWatermark to item 5 of parts
			if (count of parts) >= 8 then set logoPath to item 8 of parts

			if i is 1 then
				set thisSlide to current slide of theDoc
			else
				set thisSlide to make new slide at end of slides of theDoc with properties {base slide:master slide "Title & Bullets" of theDoc}
			end if

			if slideType is "chapter" then
				set base slide of thisSlide to master slide "Title - Center" of theDoc
				my addBackgroundRectangle(thisSlide, slideWidth, slideHeight, {65535, 60909, 14906})
			else
				set base slide of thisSlide to master slide "Title & Bullets" of theDoc
				my addBackgroundRectangle(thisSlide, slideWidth, slideHeight, {65535, 65535, 65535})
			end if

			try
				set object text of default title item of thisSlide to slideTitle
				set color of object text of default title item of thisSlide to {0, 0, 0}
			end try
			try
				set object text of default body item of thisSlide to slideBody
				set color of object text of default body item of thisSlide to {0, 0, 0}
			end try
			try
				set presenter notes of thisSlide to slideNotes
			end try

			if shouldWatermark is "true" then
				my addLogoWatermark(thisSlide, logoPath, slideWidth)
			end if
		end repeat

		save theDoc in POSIX file outputPath
		close theDoc saving yes
	end tell
end run

on addBackgroundRectangle(thisSlide, slideWidth, slideHeight, fillRGB)
	tell application "Keynote"
		try
			set bgShape to make new shape at beginning of shapes of thisSlide with properties {shape type:rectangle, position:{0, 0}, width:slideWidth, height:slideHeight}
			set background fill type of bgShape to color fill
			set background color of bgShape to fillRGB
		end try
	end tell
end addBackgroundRectangle

on addLogoWatermark(thisSlide, logoPath, slideWidth)
	tell application "Keynote"
		try
			set logoItem to make new image at end of images of thisSlide with properties {file:POSIX file logoPath}
			set width of logoItem to 48
			set height of logoItem to 51
			set position of logoItem to {slideWidth - 70, 20}
			set opacity of logoItem to 70
		end try
	end tell
end addLogoWatermark
